version: 0.2

phases:
  install:
    commands:
      - n $(cat .nvmrc)
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync dist/ s3://stg-trust-pay-payment/ --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
