name: Payment Site

on:
  push:
    branches:
      - staging-paymentsite

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.17.0'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build the project
      run: npm run build

    - name: Deploy to S3
      uses: aws-actions/s3-sync-action@v1.1.0
      with:
        bucket: ${{ secrets.AWS_S3_BUCKET }}
        region: ${{ secrets.AWS_REGION }}
        source-dir: ./dist
        delete: true
